const data = [
  {
    date: "25 April 2014",
    city: "Bogota",
    country: "Colombia",
    venue: "Estadio El Campín",
    openingAct: "El Freaky",
    attendance: "40,935 / 40,935",
  },
  {
    date: "27 April 2014",
    city: "Lima",
    country: "Peru",
    venue: "Estadio Nacional",
    openingAct: "Abraham Mateo",
    attendance: "32,601 / 32,601",
  },
  {
    date: "30 April 2014",
    city: "Santiago",
    country: "Chile",
    venue: "Estadio Nacional",
    openingAct: "Abraham Mateo",
    attendance: "67,324 / 67,324",
  },
  {
    date: "1 May 2014",
    city: "Santiago",
    country: "Chile",
    venue: "Estadio Nacional",
    openingAct: "Abraham Mateo",
    attendance: "67,324 / 67,324",
  },
  {
    date: "3 May 2014",
    city: "Buenos Aires",
    country: "Argentina",
    venue: "José Amalfitani Stadium",
    openingAct: "Sonus",
    attendance: "70,622 / 70,622",
  },
  {
    date: "4 May 2014",
    city: "Buenos Aires",
    country: "Argentina",
    venue: "José Amalfitani Stadium",
    openingAct: "Sonus",
    attendance: "70,622 / 70,622",
  },
  {
    date: "6 May 2014",
    city: "Montevideo",
    country: "Uruguay",
    venue: "Estadio Centenario",
    openingAct: "Sonus",
    attendance: "30,958 / 30,958",
  },
  {
    date: "8 May 2014",
    city: "Rio de Janeiro",
    country: "Brazil",
    venue: "Parque dos Atletas",
    openingAct: "P9",
    attendance: "40,087 / 40,087",
  },
  {
    date: "10 May 2014",
    city: "São Paulo",
    country: "Brazil",
    venue: "Estádio do Morumbi",
    openingAct: "P9",
    attendance: "102,792 / 102,792",
  },
  {
    date: "11 May 2014",
    city: "São Paulo",
    country: "Brazil",
    venue: "Estádio do Morumbi",
    openingAct: "P9",
    attendance: "102,792 / 102,792",
  },
  {
    date: "23 May 2014",
    city: "Dublin",
    country: "Colombia",
    venue: "Croke Park",
    openingAct: "5 Seconds of Summer",
    attendance: "235,008 / 235,008",
  },
  {
    date: "24 May 2014",
    city: "Dublin",
    country: "Ireland",
    venue: "Croke Park",
    openingAct: "5 Seconds of Summer",
    attendance: "235,008 / 235,008",
  },
  {
    date: "25 May 2014",
    city: "Dublin",
    country: "Ireland",
    venue: "Croke Park",
    openingAct: "5 Seconds of Summer",
    attendance: "235,008 / 235,008",
  },
  {
    date: "28 May 2014",
    city: "Sunderland",
    country: "England",
    venue: "	Stadium of Light",
    openingAct: "5 Seconds of Summer",
    attendance: "51,231 / 51,231",
  },
  {
    date: "30 May 2014",
    city: "Manchester",
    country: "England",
    venue: "Etihad Stadium",
    openingAct: "5 Seconds of Summer",
    attendance: "158,579 / 158,579",
  },
  {
    date: "31 May 2014",
    city: "Manchester",
    country: "England",
    venue: "Etihad Stadium",
    openingAct: "5 Seconds of Summer",
    attendance: "158,579 / 158,579",
  },
  {
    date: "1 June 2014",
    city: "Manchester",
    country: "England",
    venue: "Etihad Stadium",
    openingAct: "5 Seconds of Summer",
    attendance: "158,579 / 158,579",
  },
  {
    date: "3 June 2014",
    city: "Edinburgh",
    country:"Scotland" ,
    venue: "Murrayfield Stadium	",
    openingAct: "5 Seconds of Summer",
    attendance: "64,623 / 64,623",
  },
  {
    date: "6 June 2014",
    city: "London",
    country: "England",
    venue: "Wembley Stadium",
    openingAct: "5 Seconds of Summer",
    attendance: "236,566 / 236,566",
  },
  {
    date: "7 June 2014",
    city: "London",
    country: "England",
    venue: "Wembley Stadium",
    openingAct: "5 Seconds of Summer",
    attendance: "236,566 / 236,566",
  },
  {
    date: "8 June 2014",
    city: "London",
    country: "England",
    venue: "Wembley Stadium",
    openingAct: "5 Seconds of Summer",
    attendance: "236,566 / 236,566",
  },
  {
    date: "13 June 2014",
    city: "Stockholm",
    country: "Sweden",
    venue: "Friends Arena",
    openingAct: "5 Seconds of Summer",
    attendance: "88,978 / 88,978",
  },
  {
    date: "14 June 2014",
    city: "Stockholm",
    country: "Sweden",
    venue: "Friends Arena",
    openingAct: "5 Seconds of Summer",
    attendance: "88,978 / 88,978",
  },
  {
    date: "16 June 2014",
    city: "Copenhagen",
    country: "Denmark",
    venue: "Parken Stadium",
    openingAct: "McBusted",
    attendance: "83,577 / 83,577",
  },
  {
    date: "17 June 2014",
    city: "Copenhagen",
    country: "Denmark",
    venue: "Parken Stadium",
    openingAct: "McBusted",
    attendance: "83,577 / 83,577",
  },
  {
    date: "20 June 2014",
    city: "Paris",
    country: "France",
    venue: "Stade de France",
    openingAct: "5 Seconds of Summer",
    attendance: "114,172 / 114,172",
  },
  {
    date: "21 June 2014",
    city: "Paris",
    country: "France",
    venue: "Stade de France",
    openingAct: "5 Seconds of Summer",
    attendance: "114,172 / 114,172",
  },
  {
    date: "24 June 2014",
    city: "Amsterdam",
    country: "Netherlands",
    venue: "Amsterdam Arena",
    openingAct: "5 Seconds of Summer",
    attendance: "103,551 / 103,551",
  },
  {
    date: "25 June 2014",
    city: "Amsterdam",
    country: "Netherlands",
    venue: "Amsterdam Arena",
    openingAct: "5 Seconds of Summer",
    attendance: "103,551 / 103,551",
  },
  {
    date: "28 June 2014",
    city: "Milan",
    country: "Italy",
    venue: "San Siro",
    openingAct: "5 Seconds of Summer",
    attendance: "115,931 / 115,931",
  },  
  {
    date: "29 June 2014",
    city: "Milan",
    country: "Italy",
    venue: "San Siro",
    openingAct: "5 Seconds of Summer",
    attendance: "115,931 / 115,931",
  },  
  {
    date: "2 July 2014",
    city: "Düsseldorf",
    country: "Germany",
    venue: "Esprit Arena",
    openingAct: "5 Seconds of Summer",
    attendance: "44,684 / 44,684",
  },  
  {
    date: "4 July 2014",
    city: "Bern",
    country: "Switzerland",
    venue: "Stade de Suisse",
    openingAct: "5 Seconds of Summer",
    attendance: "31,037 / 31,037",
  },  
  {
    date: "6 July 2014",
    city: "Turin",
    country: "Italy",
    venue: "Stadio Olimpico",
    openingAct: "5 Seconds of Summer",
    attendance: "38,430 / 38,430",
  },  
  {
    date: "8 July 2014",
    city: "Barcelona",
    country: "Spain",
    venue: "Estadi Olímpic Lluís Companys",
    openingAct: "5 Seconds of Summer",
    attendance: "40,333 / 40,333",
  },  
  {
    date: "10 July 2014",
    city: "Madrid",
    country: "Spain",
    venue: "Estadio Vicente Calderón",
    openingAct: "5 Seconds of Summer",
    attendance: "65,186 / 65,186",
  },  
  {
    date: "11 July 2014",
    city: "Madrid",
    country: "Spain",
    venue: "Estadio Vicente Calderón",
    openingAct: "5 Seconds of Summer",
    attendance: "65,186 / 65,186",
  },  
  {
    date: "13 July 2014",
    city: "Porto",
    country: "Portugal",
    venue: "	Estádio do Dragão",
    openingAct: "D.A.M.A",
    attendance: "45,001 / 45,001",
  },
];

function createTableRow(rowData) {
  const { date, city, country, venue, openingAct, attendance } = rowData;
  return ` <tr>
    <th scope="col" ">${date}</th>
    <th scope="col" ">${city}</th>
    <th scope="col" ">${country}</th>
    <th scope="col" ">${venue}</th>
    <th scope="col" ">${openingAct}</th>
    <th scope="col" ">${attendance}</th>
  </tr>`;
}

(() => {
  const table = document.querySelector("table");
  const tableContent = table.innerHTML;

  const tableRows = data.map((row) => createTableRow(row));

  table.innerHTML = tableContent + tableRows.join("");
})();